# Generated by Django 6.1.1 on 2026-09-15 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ORDER_PLACED', 'Order Placed'), ('ORDER_CONFIRMED', 'Order Confirmed'), ('ORDER_PROCESSING', 'Order Processing'), ('ORDER_SHIPPED', 'Order Shipped'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('ORDER_DELIVERED', 'Order Delivered'), ('ORDER_CANCELLED', 'Order Cancelled'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURN_APPROVED', 'Return Approved'), ('RETURN_REJECTED', 'Return Rejected'), ('RETURN_PICKED_UP', 'Return Picked Up'), ('RETURN_RECEIVED', 'Return Received'), ('REFUND_APPROVED', 'Refund Approved'), ('REFUND_PROCESSING', 'Refund Processing'), ('REFUND_COMPLETED', 'Refund Completed'), ('REFUND_FAILED', 'Refund Failed'), ('SELLER_REGISTERED', 'Seller Registered'), ('SELLER_APPROVED', 'Seller Approved'), ('SELLER_REJECTED', 'Seller Rejected'), ('NEW_ORDER_SELLER', 'New Order for Seller'), ('SUSPICIOUS_RETURN', 'Suspicious Return'), ('SYSTEM', 'System Notification')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('reference_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('reference_type', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_f39341_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx')],
            },
        ),
    ]
