# Generated by Django 6.1.1 on 2026-09-15 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='village',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.CreateModel(
            name='SellerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('BUSINESS_REGISTRATION', 'Business Registration'), ('LICENSE', 'License'), ('IDENTITY_PROOF', 'Identity Proof'), ('ADDRESS_PROOF', 'Address Proof'), ('TAX_DOCUMENT', 'Tax Document'), ('OTHER', 'Other')], max_length=40)),
                ('document_number', models.CharField(blank=True, default='', max_length=100)),
                ('document_file', models.FileField(upload_to='seller_documents/%Y/%m/')),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('verification_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sellers.sellerprofile')),
            ],
        ),
    ]
