# Generated by Django 6.1.1 on 2026-09-15 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('DAMAGED', 'Damaged Product'), ('WRONG_PRODUCT', 'Wrong Product'), ('EXPIRED', 'Expired Product'), ('MISSING', 'Missing Product'), ('NOT_AS_DESCRIBED', 'Product Not As Described'), ('QUALITY_ISSUE', 'Quality Issue'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PICKUP_ASSIGNED', 'Pickup Assigned'), ('PICKED_UP', 'Picked Up'), ('RECEIVED', 'Received'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('SUSPICIOUS', 'Suspicious')], default='REQUESTED', max_length=30)),
                ('refund_status', models.CharField(choices=[('NOT_APPLICABLE', 'Not Applicable'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed')], default='NOT_APPLICABLE', max_length=30)),
                ('suspicious', models.BooleanField(default=False)),
                ('suspicious_reason', models.TextField(blank=True, default='')),
                ('admin_note', models.TextField(blank=True, default='')),
                ('seller_note', models.TextField(blank=True, default='')),
                ('pickup_address', models.TextField(blank=True, default='')),
                ('pickup_pincode', models.CharField(blank=True, default='', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to='orders.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to='orders.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_type', models.CharField(choices=[('CUSTOMER_PRODUCT', 'Customer Product Photo'), ('CUSTOMER_LABEL', 'Customer Label Photo'), ('CUSTOMER_EXPIRY', 'Customer Expiry/Batch Photo'), ('PICKUP', 'Pickup Photo'), ('RECEIVED', 'Received Product Photo'), ('RECEIVED_LABEL', 'Received Label Photo'), ('RECEIVED_EXPIRY', 'Received Expiry/Batch Photo'), ('OTHER', 'Other Photo')], max_length=30)),
                ('image', models.ImageField(upload_to='return_proofs/%Y/%m/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='returns.returnrequest')),
            ],
        ),
    ]
