# Generated by Django 6.1.1 on 2026-09-15 18:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('SEEDS', 'Seeds'), ('CROP_PROTECTION', 'Crop Protection Products'), ('SMALL_IRRIGATION', 'Small Irrigation Products')], max_length=30)),
                ('subcategory', models.CharField(blank=True, default='', max_length=150)),
                ('brand', models.CharField(blank=True, default='', max_length=150)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(max_length=50)),
                ('stock_quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('sku', models.CharField(blank=True, default='', max_length=100)),
                ('suitable_crops', models.JSONField(blank=True, default=list)),
                ('target_pest_disease', models.TextField(blank=True, default='')),
                ('usage_application', models.TextField(blank=True, default='')),
                ('manufacturer_details', models.TextField(blank=True, default='')),
                ('license_product_number', models.CharField(blank=True, default='', max_length=150)),
                ('verified_label', models.FileField(blank=True, null=True, upload_to='product_labels/%Y/%m/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=20)),
                ('verification_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/%Y/%m/')),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='product_videos/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='products.product')),
            ],
        ),
    ]
